### ISSUE TITLE
Material for the conference talk.

### ISSUE THREAD

**Issue by lorbax** [dodomorandi/lending-async-iterators-rustlab2024#1]
Hi!
Your talk was very interesting. Is there some recording of it? Would be cool to link it in this repo

**Comment by dodomorandi** [comment]
Thank you, I am glad you appreciated it!
The official videos are going to be released by the RustLab team, but we probably need to wait for a while.

I am going to keep the issue open, and I will add the link to the video as soon as it is published.

**Comment by dodomorandi** [comment]
@lorbax I added the link to the video in the README.
